# Generated by Django 3.2 on 2021-05-11 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_question_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='instruction',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
